{% set name = "requests-cache" %}
{% set version = "0.5.1" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "b423d1eb16e8fbc99e0280e618a2676d33c8aba77652a08b740e97fc9ffc627f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - requests >=1.1.0

test:
  imports:
    - requests_cache
    - requests_cache.backends
    - requests_cache.backends.storage

about:
  home: https://github.com/reclosedev/requests-cache/
  license_file: LICENSE
  license: BSD 2-Clause
  license_family: BSD
  summary: 'Persistent cache for requests library'
  dev_url: https://github.com/reclosedev/requests-cache/
  doc_url: https://requests-cache.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
