{% set name = "requests-cache" %}
{% set version = "0.6.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_val = "ba9b8b7893b15464d2bd35c40098c6f7561d77416068f15932ea9d223e1559ed" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - requests >=1.1.0

test:
  imports:
    - requests_cache
    - requests_cache.backends
    - requests_cache.backends.storage

about:
  home: https://github.com/reclosedev/requests-cache/
  license_file: LICENSE
  license: BSD 2-Clause
  license_family: BSD
  summary: Persistent cache for requests library
  dev_url: https://github.com/reclosedev/requests-cache/
  doc_url: https://requests-cache.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
