appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
travis:
  secure:
    BINSTAR_TOKEN: EJZxPPFTZ57XO1DKWpt8UQPPRNAGwvZj3vVeYfhA30VpDdcS95QuUzf59wGuuMkMct5drlEX4wFNNldBptOWt8MREGKzYAsYncAoO9yh7Ti+8Nd56Emtc8FjTlPj/ruN8FWeaOtJGXxTiRR/HuZ4YLBusk2hf79scykV2USWQqbDNowB3he+/rrvS/x0ZLoblo6BiCYP9DsWInwZTWy8S7NbhQsRTj2b+sKX21JmyxRxKrJu2HwBAUdAUSXsk+/9EiEzYPMaXtpHi0W6HxtZahqkVSCUr8RBHTOMsKG46uSB3HpvsnpLn5DhDlsiZ0n6u0mNcY2XCNOI2mqJDXrPn03Jzq6Cy+ymlLTdcb4iekTn/SNeZOOVP/GyIlzvXq123nwsiraSWVBcYoSGPEW4zxDUiW1qh1yZvfU35hzc9we6JxU6ISy0Zge6qj/AQxrpHtV40vcFp+H576S1O6aFmZLjyQVEL/uxtnvawvySgISXPV0gdjAA/fMTOPtWAd6eVT3OPe2LDk2vv+5fWDLipfyYjbXbjCgtyaTgtnLOkcCe0VYsOCUHslJZZvoW5ISvzCgPKBt5mSPzQ/nGe/E853QD5C52dkNsxeM5arLuMRgeeg1C4ePJCkW4BcXm4vV/sIjVfuPumjlagkWI/RtNOoiTxWT+yg0tukcdRqwCY8E=
